<!-- Copyright (c) 2026 Neil Colvin. MIT License; see ../LICENSE. -->
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net472;net10.0-windows</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<WarningsAsErrors>$(WarningsAsErrors);CS4014</WarningsAsErrors>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
		<PackageReference Include="NUnit" Version="5.0.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.3.0" PrivateAssets="all" />
		<PackageReference Include="NUnit.Analyzers" Version="4.14.0" PrivateAssets="all" />
		<ProjectReference Include="../TeslaPowerwallLibrary.TestConsole/TeslaPowerwallLibrary.TestConsole.csproj" />
	</ItemGroup>
	<Target Name="RemoveUnusedWebView2UiReferences" BeforeTargets="ResolveAssemblyReferences"
			Condition=" '$(UseWPF)' != 'true' And '$(UseWindowsForms)' != 'true' ">
		<ItemGroup>
			<Reference Remove="@(Reference)"
						Condition="'%(Reference.Filename)' == 'Microsoft.Web.WebView2.Wpf' Or '%(Reference.Filename)' == 'Microsoft.Web.WebView2.WinForms'" />
		</ItemGroup>
	</Target>
</Project>
