<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<WarningsAsErrors>$(WarningsAsErrors);CS4014</WarningsAsErrors>
		<NoWarn>$(NoWarn);NU1701</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
		<PackageReference Include="NUnit" Version="5.0.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.3.0" PrivateAssets="all" />
		<PackageReference Include="NUnit.Analyzers" Version="4.14.0" PrivateAssets="all" />
		<ProjectReference Include="..\TeslaPowerwallLibrary.App\TeslaPowerwallLibrary.App.csproj" />
	</ItemGroup>
</Project>
